### ISSUE TITLE
AutoImmanence.lua

### ISSUE THREAD

**Issue by qe58hmr** [jubk/ffxi-gearswap#2]
hi there, i loaded the lua duno how to start it is this only sch lua? any tips how to start the lua will help thank you

**Comment by jubk** [comment]
> hi there, i loaded the lua duno how to start it is this only sch lua? any tips how to start the lua will help thank you

I just made a change to [AutoImmanence.lua](https://github.com/jubk/ffxi-gearswap/blob/master/common/AutoImmanence.lua) making it easier to import into existing gearswap luas. Instructions on how to do that are at the top of the file. You can also take a look at my SCH lua for a working example: [SCH.lua](https://github.com/jubk/ffxi-gearswap/blob/master/Miaw/SCH.lua).
